version: "2"
services:
  db:
    container_name: shoppinglist_db
    image: postgres
    ports:
      - "15432:5432"
  api:
    build: .
    command: python3 code/manage.py runserver 0.0.0.0:8080
    container_name: shoppinglist_api
    volumes:
      - ./api:/code
    ports:
      - "8080:8080"
    depends_on:
      - db